// <auto-generated />
using EasyGames.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyGames.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250916073215_addImageUrl")]
    partial class addImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyGames.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Games"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Toys"
                        });
                });

            modelBuilder.Entity("EasyGames.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Harry Potter is the \"Boy Who Lived,\" a young wizard with distinctive green eyes, messy black hair, and a lightning bolt-shaped scar on his forehead, who discovers his true identity after surviving an attack by the dark wizard Lord Voldemort as a baby",
                            ImageUrl = "",
                            Name = "Harry Potter",
                            Price = 0.01m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "The Witcher 3: Wild Hunt is an open-world action RPG where players control Geralt of Rivia, a monster hunter searching for his adoptive daughter, Ciri, who is being pursued by the otherworldly Wild Hunt.",
                            ImageUrl = "",
                            Name = "The Witcher 3",
                            Price = 0.02m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Make Cool Tricks YOO",
                            ImageUrl = "",
                            Name = "Yoyo",
                            Price = 0.03m
                        });
                });

            modelBuilder.Entity("EasyGames.Models.Product", b =>
                {
                    b.HasOne("EasyGames.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
